# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f94a17d91d98ff3021a86ff834ab2125dfa8435376eed0499296d851aa2654aae914ecf2a501118cb229c47313a5367df955f4899fb74667f0dc184191836301

test:
  secret_key_base: 69a2f7e245d0fae1c42268f46ea7b18471d892ebdd15fb469522030241ad8245e6379d2bbd22edb13dc5e67c4172c6469e8a57565e129b6587db167504a1a803

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
